logging:
  level:
    org.springframework.boot.autoconfigure.logging: ERROR
    ch.qos.logback: ERROR

currency:
  available:
    - "RUB"
cost:
  rub:
    cubicMeter: 800
    perKg: 400
    minimal: 350

coordinates:
  latitudeMin: 45
  latitudeMax: 65
  longitudeMin: 30
  longitudeMax: 96



